### ISSUE TITLE
Right Following

### ISSUE THREAD

**Issue by searri** [GW-Robotics/2018-Firefighter#38]
Algorithm to follow the right wall

**Comment by ippomp** [comment]
'''c
counter = 1
    while counter < 2:{
      if (frontultrasonic.getdistance()>2 && rightultrasonic.getdistance()<2){
        moveslightleft();
        delay(500);
        //move left diagnal
        moveslightright().wait(rightultrasonic.getdistance()<2);
        delay(500);
        //move diagnol towards the wall until your close to the wall
        }
      while(rightultrasonic.getdistance()>2){
        //if there is no right wall turn right
        moveright();
        delay(500);
        count 1}}
    while counter > 2: {
      if (frontultrasonic.getdistance()>2 && lefttultrasonic.getdistance()<2){
        moveslightright();
        delay(500);
        //move left diagnal
        moveslightleft().wait(leftultrasonic.getdistance()<2);
        delay(500);}
      while(leftultrasonic.getdistance()>2){
        //if there is no left wall turn left
        moveright();
        delay(500);
        count 1;
  '''c
